version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: backend
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    container_name: frontend
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
